### ISSUE TITLE
SetTorrentsLocation fails if the location contains a space

### ISSUE THREAD

**Issue by TimBashford** [teug91/qBittorrentSharp#2]
SetTorrentsLocation fails when trying to update a torrent's location to one which contains a space.  This is seemingly because FormUrlEncodedContent will encode spaces as "+" which the API doesn't parse as a space on the other end.  The API does parse %20, however, so I quickly bodged something with Uri.EscapeDataString to encode the location, then using a StringContent rather than a FormUrlEncodedContent for this call.

**Comment by teug91** [comment]
Thanks. Should be fixed with [commit 3b8289a](https://github.com/teug91/qBittorrentSharp/commit/3b8289a11cbd28dde7156b8abccfd00c97d54f69).
